app_module = "demo_commandlink"
app_class = "CommandOrchestratorApp"
module_path = "./scripts"

[[step]]
type = "capture"

[[step]]
type = "delay"
seconds = 1.0

[[step]]
type = "press"
key = "1"

[[step]]
type = "capture"